require 'hoe'

# require './lib/0xfacet/version.rb'


Hoe.spec '0xfacet-rubidity' do

  self.version =   '0.0.1'

  self.summary = '0xfacet-rubidity - rubidity o.g. facet vm contract programming language interpreter'
  self.description = summary

  self.urls    = { home: 'https://github.com/s6ruby/rubidity.review' }

  self.author  = 'Gerald Bauer'
  self.email   = 'gerald.bauer@gmail.com'

  # switch extension to .markdown for gihub formatting
  self.readme_file  = 'README.md'
  self.history_file = 'CHANGELOG.md'

  self.extra_deps = [
    ['0xfacet-typed', '>= 0.0.1'],
  ]


  self.licenses = ['Public Domain']

  self.spec_extras = {
    required_ruby_version: '>= 2.3'
  }
end
