require 'hoe'

require './lib/0xfacet/typed/version.rb'


Hoe.spec '0xfacet-typed' do

  self.version =   Facet::Module::Typed::VERSION

  self.summary = '0xfacet-typed - solidity-like value and reference types for rubidity o.g.'
  self.description = summary

  self.urls    = { home: 'https://github.com/s6ruby/rubidity.review' }

  self.author  = 'Gerald Bauer'
  self.email   = 'gerald.bauer@gmail.com'

  # switch extension to .markdown for gihub formatting
  self.readme_file  = 'README.md'
  self.history_file = 'CHANGELOG.md'

  self.extra_deps = [
    ## ['0xfacet'],
    ['activesupport', '>= 7.0'],
  ]


  self.licenses = ['Public Domain']

  self.spec_extras = {
    required_ruby_version: '>= 2.3'
  }
end
